[build-system]
requires = ["setuptools", "torch"]
build-backend = "setuptools.build_meta"

[project]
name = "01_Kernel_basics"
version = "0.1.0"
description = "My first kernel function"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []
